name: Nightly Build

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            # Setup .NET SDK
            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '6.0.x'
                include-prerelease: true

            # Install DotNet Script
            - name: Install DotNet Script
              run: dotnet tool install -g dotnet-script

            # Build Ancient Mysteries Source Generator
            #- name: Build Ancient Mysteries Mod
            #  run: dotnet build AncientMysteries.SourceGenerator\AncientMysteries.SourceGenerator.csproj -c Release --nologo

            # Build Ancient Mysteries Code Analyzers
            #- name: Build Ancient Mysteries Mod
            #  run: dotnet build AncientMysteries.Analyzers\AncientMysteries.Analyzers.csproj -c Release --nologo

            # Build Ancient Mysteries Mod
            - name: Build Ancient Mysteries Mod
              run: dotnet build .\AncientMysteries\AncientMysteries.csproj -c Release -o ".\buildOutput" --nologo /p:NoPostBuild=true

            # Pack built files into single zip
            - name: Pack built files
              run: Compress-Archive -Path ".\buildOutput\*" -CompressionLevel Optimal -DestinationPath ".\AncientMysteries.zip"

            # Upload as nightly-build
            - name: Upload as nightly-build
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                automatic_release_tag: "latest-nightly"
                prerelease: true
                title: "Nightly Build"
                files: AncientMysteriesMod.zip

            # File Tree for action debugging
            #- name: File Tree for action debugging
            #  run: tree
